### ISSUE TITLE
Enabling code scanning for Jamulus source code

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#822]
Github supports code scanning since a while now:

https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository (see also this https://github.blog/2020-09-30-code-scanning-is-now-available/ and this https://github.com/corrados/jamulus/issues/593).

We should make use of that in the Jamulus project.

**Comment by corrados** [comment]
@ann0see Is this something you could take care of?

**Comment by ann0see** [comment]
It sounds interesting, but I would prefer to focus um the installer, maybe automatic building for windows and Mac and potentially a bit more iOS support first. So I think it would be better if someone else had a look at this.

**Comment by corrados** [comment]
No hurry with that feature :-)

**Comment by pljones** [comment]
OK, it looks like there's no Qt support.  The scanner tries to run a build -- the built in auto-build fails to identify the project as using Qt/qmake/Jamulus.pro and running qmake directly fails.

**Comment by pljones** [comment]
Oh... `runs-on: ubuntu-latest` -- if there's a Qt image, maybe it can use that...

**Comment by pljones** [comment]
It looks like we'd need a [self-hosted runner](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners) running the appropriate build environment(s).

It's possibly going to take a little while to work out what would be involved -- it's probably _not_ a good idea to run the self-hosted runner on a Jamulus server box to avoid CPU contention.

**Comment by pljones** [comment]
I just realised I did the change on corrados/jamulus, not pljones/jamulus!  Sorry..!

**Comment by pljones** [comment]
> [Self-hosted runner security with public repositories](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories)

That points out a few potential issues with a self-hosted runner, from a security perspective.  Using a single-use, on demand VM would probably alleviate them, I think.  Anyone got recommendations for providers?  (Ideally with free-forever plans, of course...)

**Comment by corrados** [comment]
Is it not possible to run in entirely on Github? Do you need external resources to run it? In this case I actually would not spend time on it. I thought that you simply setup a configuration script with your setting and then a job is run at Github which checks your code. So, it seem I had not made my homework...

**Comment by ann0see** [comment]
Isn't it possible to install qt via apt?

**Comment by pljones** [comment]
Github's "ubuntu-latest" runner doesn't have Qt installed.  So no, it's not possible to run it without additional resources.

Yes, I suppose all the dependencies could be fetched...  I'll look into that.

**Comment by pljones** [comment]
Getting better...
```
Fetched 43.5 MB in 1s (30.6 MB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libi/libinput/libinput-bin_1.10.4-1ubuntu0.18.04.1_amd64.deb  404  Not Found [IP: 52.250.76.244 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libi/libinput/libinput10_1.10.4-1ubuntu0.18.04.1_amd64.deb  404  Not Found [IP: 52.250.76.244 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```
...but still not there.  The versions of `libinput-bin` and `libinput10` aren't on the Ubuntu repo any more.  I'm trying with a full upgrade... it might only need an update (full upgrade takes longer than I anticipated...).

**Comment by pljones** [comment]
Excellent - thanks @ann0see, it builds!

**Comment by ann0see** [comment]
I thought the VM had 7GB of RAM: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners

**Comment by pljones** [comment]
Changing from `make -j` to `make` seemed to fix it.  `make -j` might have been a bit excessive for a 2 core CPU.  I'm trying the Windows and MacOS builds, now.

**Comment by ann0see** [comment]
I got Qt installed on Windows the install qt action:

```

- name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          dir: '${{ github.workspace }}'
          arch: 'win64_msvc2019_64'
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          dir: '${{ github.workspace }}'
          arch: 'win32_msvc2019'

```

**Comment by pljones** [comment]
Looks like I can't use that within the `steps`:
```
    steps:
    - name: Install Qt
        uses: jurplel/install-qt-action@v2  ;# ** Bad intention of a mapping entry **
        with:
          version: '5.15.2'
          dir: '${{ github.workspace }}'
          arch: 'win64_msvc2019_64'

    - name: Checkout repository
      uses: actions/checkout@v2
```
